# Generated by Django 5.0 on 2023-12-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
